# Generated by Django 3.1 on 2020-09-28 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('capacity', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('time', models.TimeField()),
                ('online', models.BooleanField(default=True)),
                ('instructors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='user.instructorprofile')),
                ('participants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='user.participantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('dropped_at', models.DateTimeField(null=True)),
                ('seminar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seminar', to='seminar.seminar')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
