# Generated by Django 3.1 on 2020-09-29 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='instructors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seminar', to='user.instructorprofile'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='participants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seminar', to='user.participantprofile'),
        ),
        migrations.AlterField(
            model_name='userseminar',
            name='seminar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userseminar', to='seminar.seminar'),
        ),
        migrations.AlterField(
            model_name='userseminar',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userseminar', to=settings.AUTH_USER_MODEL),
        ),
    ]
