# Generated by Django 3.1 on 2020-09-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_auto_20200929_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='userseminar',
            name='role',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
