# Generated by Django 3.1 on 2020-09-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
